# Generated by Django 4.1.5 on 2023-01-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appcod', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Subtitulo', models.CharField(max_length=50)),
                ('Resu', models.CharField(max_length=50)),
                ('Cuerpo', models.CharField(max_length=50)),
                ('Autor', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Imagen', models.ImageField(upload_to='blog')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='blog')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appcod.blog')),
            ],
        ),
    ]
