# Generated by Django 4.1.5 on 2023-01-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcod', '0003_blog_imagenblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenBlog',
        ),
    ]
